### ISSUE TITLE
What license?

### ISSUE THREAD

**Issue by MostHated** [modstam/Traffic-Simulation#1]
Hey there,
    I had sent a message on Twitter, but it was to @starvalley42. I saw this system you guys made and I thought it looked pretty neat. I looked through the files and on here but didn't see a license, is this released as MIT?

Thanks,
-MH

**Comment by modstam** [comment]
Hello!

The project itself was for a course at the Royal Institute of Technology. All of the models are owned by the school but I think it would be completely fine to use the project if you want, given that you change the models if you're doing anything commercial. The code itself would fall under AAL https://opensource.org/licenses/AAL which means you are free to use it if you want if you give proper credit if you ever end up shipping something commercial. 

I hope you can use the project to make something cool :) 
Regards,
Måns Odstam

**Comment by MostHated** [comment]
Awesome, I appreciate it! I already have all my own models and everything, I mostly was interested in the logic for following the path as well as traffic lights. I have tried out tons of different traffic things for Unity (I say tons, but actually there really are not that many, at least that are halfway decent), so I figured I would give this one a go as it looked like it might work out for me pretty well based on the video.

I did have a few questions if you didn't mind?  I was playing around with it in a test project, I have it working for the most part, but I can't quite figure out what is controlling the speed of a vehicle? One area of my test, the car starts to go super fast for some reason between the end node and the closest one to it, but the other end of the network goes super slow between the end node and its closest one.

  Also, does the length of a bezier handle in relation to the origin node make any difference or the distance from one node to another? I noticed that if I had the handle too close to the origin, the car would start to spin. I was reading through the blog and I saw you mentioned that it had to do with the distance traveled vs time passed from update and that it might happen too fast with a higher framerate. Had you tried using FixedUpdate instead of just update? I was going to try that out. 

Would a traffic light setup still work if you were to say, have a T intersection, but the 3rd line, the lower part of a T shape, if you were to instead of connecting it directly to the top of the T with a single point, but instead branched it to make a Y shape so that you could make a smooth left and right turn, would that end up working? 

Lastly, is it possible to somehow place down a single point or line segment without doing an "add" off of the already existing primary spline?


I very much thank you for your time!
-MH

**Comment by modstam** [comment]
I'll have to look into this and come back to you (we made this some years ago after all :) ). Unfortunately I am quite busy at the moment so I can probably look into this sometime tomorrow.

**Comment by MostHated** [comment]
Oh, no worries at all. I can completely understand, lol.

**Comment by modstam** [comment]
>  I was playing around with it in a test project, I have it working for the most part, but I can't quite figure out what is controlling the speed of a vehicle? 

From what I can tell, the variable CAR_EDGE_TIME in car.cs is what is controlling the speed of the car. Essentially it is saying how many seconds a car should spend on an edge (an edge is the line between two nodes). Honestly I am not sure why we made this a constant and not a variable of the length of the edge (the distance between two nodes)

> Also, does the length of a bezier handle in relation to the origin node make any difference or the distance from one node to another? I noticed that if I had the handle too close to the origin, the car would start to spin. I was reading through the blog and I saw you mentioned that it had to do with the distance traveled vs time passed from update and that it might happen too fast with a higher framerate. Had you tried using FixedUpdate instead of just update? I was going to try that out.

If I'm understanding your question correctly; the length of the handles from the origin point, or rather the position of the control nodes relative to the origin node controls how steep the curve becomes. Example seen here: https://youtu.be/F8chP-TzXLg?t=38s 
Regarding FixedUpdate -- I don't think we ever tried that actually. Give it a shot!

> Would a traffic light setup still work if you were to say, have a T intersection, but the 3rd line, the lower part of a T shape, if you were to instead of connecting it directly to the top of the T with a single point, but instead branched it to make a Y shape so that you could make a smooth left and right turn, would that end up working?

I think both a T-shape and a Y-shape should function correctly with the traffic lights. I dont think the shape of the intersection matters. Maybe @Stjerndal has more input on this? 

> Lastly, is it possible to somehow place down a single point or line segment without doing an "add" off of the already existing primary spline?

To do this I think you'd have to add another Simulator prefab and have that control a separate network which would basically be just this new line segment. I don't think that should be a problem but I'm not sure how the menu would work with several networks. 

It's pretty jarring reading code from a couple of years ago and honestly I'm scratching my head when looking at some design decisions we made. I hope you can make use of it anyways. Happy coding :)
